scene:
  original_scannet_path: /home/tcluan/D-Data/ScanNet/scans
  processed_scannet_path: /home/tcluan/D-Data/ExpLog/ScanNet_Shortcut
  start_from: 0
  end_with: 100

render:
  sensor_width: 36.0
  width: 1296
  height: 968
  zNear: 0.01
  zFar: 8.0